export const CHON_GOI_CUOC_UPDATE_PRICE_REDUX = 'CHON_GOI_CUOC_UPDATE_PRICE_REDUX';
export const NHAP_DIA_CHI_UPDATE_PRICE_REDUX = 'NHAP_DIA_CHI_UPDATE_PRICE_REDUX';
export const RESET_REDUX_GUI_HANG ='RESET_REDUX_GUI_HANG';